### PR TITLE
Creating tarball with relative pathing, starting at the base of the portable env

### PR DESCRIPTION
**Pull request by ty-i3**
Also, unifying tense with the others in l/info

### CODE REVIEW

**Comment by ty-i3** [comment]
Oh, and please ping me when this project is next released to clojars!

**Comment by sunng87** [comment]
Thanks. Sorry for late.

**Comment by sunng87** [comment]
0.2.1 has been released to clojars.

**Comment by ty-i3** [comment]
Thanks!

**Pull request merged**
